version: '3.8'

services:
  backend:
    build: ./BackEnd-Django
    ports:
      - "8000:8000"
    command: >
      sh -c "./entrypoint.sh && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings 
    volumes:
      - ./BackEnd-Django/db/:/app/db/
      - backend_uploads:/app/uploads  

  frontend:
    build: ./FrontEnd-Angular/mosquitoAPP
    ports:
      - "4242:4200"
    extra_hosts:
      - "localhost:host-gateway" 
    command: npm start -- --host 0.0.0.0 --port 4200
    depends_on:
      - backend
    volumes:
      - ./FrontEnd-Angular/mosquitoAPP:/app  
      - /app/node_modules 

volumes:
  backend_sqlite:
  backend_uploads:
