# Generated by Django 5.1.5 on 2025-02-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='UserObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosquito_img', models.ImageField(upload_to='user_mosquito_imges')),
                ('date', models.DateField(auto_now_add=True)),
                ('gps_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userObservations.location')),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'pending'), ('1', 'in-progress'), ('2', 'completed')], max_length=1)),
                ('user_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userObservations.userobservation')),
            ],
        ),
    ]
