# Generated by Django 5.1.5 on 2025-02-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userObservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='latitud',
            new_name='latitude',
        ),
    ]
