# Generated by Django 5.1.5 on 2025-02-06 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userObservations', '0002_rename_latitud_location_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobservation',
            name='gps_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='userObservations.location'),
        ),
        migrations.AlterField(
            model_name='userobservation',
            name='mosquito_img',
            field=models.ImageField(upload_to='user_mosquito_images'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_location'),
        ),
    ]
