# Generated by Django 5.1.5 on 2025-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userObservations', '0003_alter_userobservation_gps_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userobservation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
